CREATE TABLE IF NOT EXISTS hashtag_definitions (
  id SERIAL PRIMARY KEY,
  tag TEXT NOT NULL UNIQUE,
  meaning TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT 'other',
  description TEXT DEFAULT '',
  example TEXT DEFAULT '',
  sort_order INT DEFAULT 99,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Seed from PDF classification document
INSERT INTO hashtag_definitions (tag, meaning, category, description, sort_order) VALUES
  ('#hardware',    'Phần cứng',              'device',   'Check lỗi phần cứng', 1),
  ('#go168',       'Lỗi Go168',              'device',   'Thiết bị Go168', 2),
  ('#gotrack',     'Lỗi Gotrack',            'device',   'Thiết bị S400', 3),
  ('#mt99',        'Lỗi MT99',               'device',   'Thiết bị MT99', 4),
  ('#vn88',        'Lỗi VN88',               'device',   'Thiết bị VN88', 5),
  ('#dvr',         'Lỗi DVR',                'device',   'Thiết bị DVR', 6),
  ('#bw',          'Lỗi BW',                 'device',   'Thiết bị BW', 7),
  ('#c43',         'Lỗi C43',                'device',   'Thiết bị C43', 8),
  ('#h5',          'Lỗi H5',                 'device',   'Thiết bị H5', 9),
  ('#sj',          'Lỗi cây dầu Soji',       'device',   'Cây dầu Soji', 10),
  ('#fs',          'Lỗi cây dầu FS100',      'device',   'Cây dầu Đài Loan FS100', 11),
  ('#fuelsensor',  'Liên quan đến dầu',       'device',   'Check lục liên quan đến dầu', 12),
  ('#pm',          'Lỗi phần mềm',           'device',   'Lỗi do phần mềm', 13),
  ('#nc',          'No Connect',             'error',    'Lỗi mất kết nối', 20),
  ('#gsm',         'Lỗi tín hiệu mạng',      'error',    'Truyền bù, không nhận SIM', 21),
  ('#gps',         'Lỗi tín hiệu GPS',       'error',    'Lỗi GPS', 22),
  ('#sd',          'Lỗi thẻ nhớ',            'error',    'Lỗi SD card', 23),
  ('#roaming',     'Lỗi roaming',            'error',    'Xe đi nước ngoài', 24),
  ('#acc',         'Lỗi tín hiệu ACC',       'error',    'Lỗi bật/tắt khóa', 25),
  ('#rfid',        'Lỗi thẻ quẹt lái xe',    'error',    'Cả do tbi và do thẻ', 26),
  ('#pw',          'Lỗi nguồn',              'error',    'Power issue', 27),
  ('#ss',          'Lỗi cảm biến xung',      'error',    'Sensor lỗi (không phải cảm biến dầu)', 28),
  ('#dms',         'Lỗi hành vi lái xe',     'error',    'DMS - Driver Monitoring System', 29),
  ('#adas',        'Lỗi cảm biến va chạm',   'error',    'Cảm biến lệch làn, va chạm', 30),
  ('#sp',          'Hỗ trợ khách hàng',      'error',    'Support - giải thích cho khách', 31),
  ('#io',          'Lỗi tín hiệu IO',        'error',    'Tín hiệu đóng mở cửa,...', 32),
  ('#f',           'Fast (<5 phút)',          'time',     'Tốc độ xử lý dưới 5 phút', 40),
  ('#n',           'Normal (5-30 phút)',      'time',     'Tốc độ xử lý trên 5 phút', 41),
  ('#l',           'Low (>30 phút)',          'time',     'Tốc độ xử lý trên 30 phút', 42),
  ('#update',      'Update tiến độ',         'update',   'Cập nhật thời gian xử lý xong lục', 50),
  ('#dl',          'Deadline',               'update',   'Hạn hoàn thành bug từ đội PM', 51),
  ('#video',       'Lỗi video',              'software', 'Lỗi đường truyền video, ảnh', 60),
  ('#app',         'Lỗi App',                'software', 'Lỗi app VN FMS, eDriver', 61),
  ('#report',      'Lỗi báo cáo',            'software', 'Lỗi báo cáo trên FMS (không phải dầu)', 62)
ON CONFLICT (tag) DO NOTHING;
